function folderPathArray = defineFolders
%DEFINEFOLDERS Summary of this function goes here
%   Detailed explanation goes here

% GSA People Folders
% --> DC 1800F
gsaPeople1800f = {'\\ROOT\projects\GSA_Daysimeter\WashingtonDC\Daysimeter_People_Data\summer\originalData';...
    '\\ROOT\projects\GSA_Daysimeter\WashingtonDC\Daysimeter_People_Data\winter\originalData'};
% --> DC ROB
gsaPeopleRob = {'\\ROOT\projects\GSA_Daysimeter\WashingtonDC-RegionalOfficeBldg-7th&Dstreet\Daysimeter_People_Data\summer\originalData';...
    '\\ROOT\projects\GSA_Daysimeter\WashingtonDC-RegionalOfficeBldg-7th&Dstreet\Daysimeter_People_Data\winter\originalData'};
% --> Seattle
gsaPeopleSeattle = {'\\ROOT\projects\GSA_Daysimeter\Seattle_Washington\Daysimeter_People_Data\FCS_Building_1202\summer\originalData';...
    '\\ROOT\projects\GSA_Daysimeter\Seattle_Washington\Daysimeter_People_Data\FCS_Building_1202\winter\originalData';...
    '\\ROOT\projects\GSA_Daysimeter\Seattle_Washington\Daysimeter_People_Data\FCS_Building_1201\summer\originalData';...
    '\\ROOT\projects\GSA_Daysimeter\Seattle_Washington\Daysimeter_People_Data\FCS_Building_1201\winter\originalData'};
% --> Grand Junction
gsaPeopleGrandJunction = {'\\ROOT\projects\GSA_Daysimeter\GrandJunction_Colorado_site_data\Daysimeter_People_Data\summerOriginalData'};
% --> Portland
gsaPeoplePortland = {'\\ROOT\projects\GSA_Daysimeter\Portland_Oregon_site_data\Daysimeter_People_Data\summerOriginalData';...
    '\\ROOT\projects\GSA_Daysimeter\Portland_Oregon_site_data\Daysimeter_People_Data\winterOriginalData'};

% GSA Stationary Folders
% --> DC 1800F
gsaStat1800f = {'\\ROOT\projects\GSA_Daysimeter\WashingtonDC\Daysimeter_Stationary_Data\summerOriginalData';...
    '\\ROOT\projects\GSA_Daysimeter\WashingtonDC\Daysimeter_Stationary_Data\novemberOriginalData';...
    '\\ROOT\projects\GSA_Daysimeter\WashingtonDC\Daysimeter_Stationary_Data\decemberOriginalData'};
% --> DC ROB
gsaStatRob = {'\\ROOT\projects\GSA_Daysimeter\WashingtonDC-RegionalOfficeBldg-7th&Dstreet\Daysimeter_Stationary_Data\summerOriginalData'};
% --> Seattle
gsaStatSeattle = {'\\ROOT\projects\GSA_Daysimeter\Seattle_Washington\Daysimeter_Stationary_Data\Original and Corrected Files'};
% --> Grand Junction
gsaStatGrandJunction = {'\\ROOT\projects\GSA_Daysimeter\GrandJunction_Colorado_site_data\Daysimeter_Stationary_Data\summerOriginalData';...
    '\\ROOT\projects\GSA_Daysimeter\GrandJunction_Colorado_site_data\Daysimeter_Stationary_Data\summerOriginalData'};
% --> Portland
gsaStatPortland = {'\\ROOT\projects\GSA_Daysimeter\Portland_Oregon_site_data\Daysimeter_Stationary_Data\summerOriginalData';...
    '\\ROOT\projects\GSA_Daysimeter\Portland_Oregon_site_data\Daysimeter_Stationary_Data\winterOriginalData'};


folderPathArray = [gsaPeople1800f;...
                   gsaPeopleRob;...
                   gsaPeopleSeattle;...
                   gsaPeopleGrandJunction;...
                   gsaPeoplePortland;...
                   gsaStat1800f;...
                   gsaStatRob;...
                   gsaStatSeattle;...
                   gsaStatGrandJunction;...
                   gsaStatPortland];


end

